global_frame: /odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  - {name: radiationLocal,            type: "radiation_layer_namespace::RadLayer"} 
  - {name: temperatureLocal,          type: "temperature_layer_namespace::TempLayer"}
