(cl:defpackage neo_srvs-srv
  (:use )
  (:export
   "IOBOARDSETDIGOUT"
   "<IOBOARDSETDIGOUT-REQUEST>"
   "IOBOARDSETDIGOUT-REQUEST"
   "<IOBOARDSETDIGOUT-RESPONSE>"
   "IOBOARDSETDIGOUT-RESPONSE"
   "RELAYBOARDSETLCDMSG"
   "<RELAYBOARDSETLCDMSG-REQUEST>"
   "RELAYBOARDSETLCDMSG-REQUEST"
   "<RELAYBOARDSETLCDMSG-RESPONSE>"
   "RELAYBOARDSETLCDMSG-RESPONSE"
   "RELAYBOARDSETRELAY"
   "<RELAYBOARDSETRELAY-REQUEST>"
   "RELAYBOARDSETRELAY-REQUEST"
   "<RELAYBOARDSETRELAY-RESPONSE>"
   "RELAYBOARDSETRELAY-RESPONSE"
  ))

