(cl:defpackage cob_msgs-msg
  (:use )
  (:export
   "<ACCESSPOINT>"
   "ACCESSPOINT"
   "<BATTERYSERVER>"
   "BATTERYSERVER"
   "<BATTERYSERVER2>"
   "BATTERYSERVER2"
   "<BATTERYSTATE>"
   "BATTERYSTATE"
   "<BATTERYSTATE2>"
   "BATTERYSTATE2"
   "<DASHBOARDSTATE>"
   "DASHBOARDSTATE"
   "<EMERGENCYSTOPSTATE>"
   "EMERGENCYSTOPSTATE"
   "<POWERBOARDSTATE>"
   "POWERBOARDSTATE"
   "<POWERSTATE>"
   "POWERSTATE"
  ))

