// Generated by gencpp from file cob_srvs/GetPoseStampedTransformed.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_GETPOSESTAMPEDTRANSFORMED_H
#define COB_SRVS_MESSAGE_GETPOSESTAMPEDTRANSFORMED_H

#include <ros/service_traits.h>


#include <cob_srvs/GetPoseStampedTransformedRequest.h>
#include <cob_srvs/GetPoseStampedTransformedResponse.h>


namespace cob_srvs
{

struct GetPoseStampedTransformed
{

typedef GetPoseStampedTransformedRequest Request;
typedef GetPoseStampedTransformedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoseStampedTransformed
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::GetPoseStampedTransformed > {
  static const char* value()
  {
    return "ed0069a0a6ce5102fc39c3328eef052f";
  }

  static const char* value(const ::cob_srvs::GetPoseStampedTransformed&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::GetPoseStampedTransformed > {
  static const char* value()
  {
    return "cob_srvs/GetPoseStampedTransformed";
  }

  static const char* value(const ::cob_srvs::GetPoseStampedTransformed&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::GetPoseStampedTransformedRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::GetPoseStampedTransformed > 
template<>
struct MD5Sum< ::cob_srvs::GetPoseStampedTransformedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::GetPoseStampedTransformed >::value();
  }
  static const char* value(const ::cob_srvs::GetPoseStampedTransformedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::GetPoseStampedTransformedRequest> should match 
// service_traits::DataType< ::cob_srvs::GetPoseStampedTransformed > 
template<>
struct DataType< ::cob_srvs::GetPoseStampedTransformedRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::GetPoseStampedTransformed >::value();
  }
  static const char* value(const ::cob_srvs::GetPoseStampedTransformedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::GetPoseStampedTransformedResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::GetPoseStampedTransformed > 
template<>
struct MD5Sum< ::cob_srvs::GetPoseStampedTransformedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::GetPoseStampedTransformed >::value();
  }
  static const char* value(const ::cob_srvs::GetPoseStampedTransformedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::GetPoseStampedTransformedResponse> should match 
// service_traits::DataType< ::cob_srvs::GetPoseStampedTransformed > 
template<>
struct DataType< ::cob_srvs::GetPoseStampedTransformedResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::GetPoseStampedTransformed >::value();
  }
  static const char* value(const ::cob_srvs::GetPoseStampedTransformedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_GETPOSESTAMPEDTRANSFORMED_H
