// Generated by gencpp from file cob_srvs/SetDefaultVel.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_SETDEFAULTVEL_H
#define COB_SRVS_MESSAGE_SETDEFAULTVEL_H

#include <ros/service_traits.h>


#include <cob_srvs/SetDefaultVelRequest.h>
#include <cob_srvs/SetDefaultVelResponse.h>


namespace cob_srvs
{

struct SetDefaultVel
{

typedef SetDefaultVelRequest Request;
typedef SetDefaultVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDefaultVel
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::SetDefaultVel > {
  static const char* value()
  {
    return "a7159156625f755343070ad39bfaf3a3";
  }

  static const char* value(const ::cob_srvs::SetDefaultVel&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::SetDefaultVel > {
  static const char* value()
  {
    return "cob_srvs/SetDefaultVel";
  }

  static const char* value(const ::cob_srvs::SetDefaultVel&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::SetDefaultVelRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::SetDefaultVel > 
template<>
struct MD5Sum< ::cob_srvs::SetDefaultVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetDefaultVel >::value();
  }
  static const char* value(const ::cob_srvs::SetDefaultVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetDefaultVelRequest> should match 
// service_traits::DataType< ::cob_srvs::SetDefaultVel > 
template<>
struct DataType< ::cob_srvs::SetDefaultVelRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetDefaultVel >::value();
  }
  static const char* value(const ::cob_srvs::SetDefaultVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::SetDefaultVelResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::SetDefaultVel > 
template<>
struct MD5Sum< ::cob_srvs::SetDefaultVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetDefaultVel >::value();
  }
  static const char* value(const ::cob_srvs::SetDefaultVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetDefaultVelResponse> should match 
// service_traits::DataType< ::cob_srvs::SetDefaultVel > 
template<>
struct DataType< ::cob_srvs::SetDefaultVelResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetDefaultVel >::value();
  }
  static const char* value(const ::cob_srvs::SetDefaultVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_SETDEFAULTVEL_H
