// Generated by gencpp from file cob_srvs/SetJointTrajectory.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_SETJOINTTRAJECTORY_H
#define COB_SRVS_MESSAGE_SETJOINTTRAJECTORY_H

#include <ros/service_traits.h>


#include <cob_srvs/SetJointTrajectoryRequest.h>
#include <cob_srvs/SetJointTrajectoryResponse.h>


namespace cob_srvs
{

struct SetJointTrajectory
{

typedef SetJointTrajectoryRequest Request;
typedef SetJointTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointTrajectory
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::SetJointTrajectory > {
  static const char* value()
  {
    return "098b55597ea8f8573e4c0bab09cb9bce";
  }

  static const char* value(const ::cob_srvs::SetJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::SetJointTrajectory > {
  static const char* value()
  {
    return "cob_srvs/SetJointTrajectory";
  }

  static const char* value(const ::cob_srvs::SetJointTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::SetJointTrajectoryRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::SetJointTrajectory > 
template<>
struct MD5Sum< ::cob_srvs::SetJointTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetJointTrajectory >::value();
  }
  static const char* value(const ::cob_srvs::SetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetJointTrajectoryRequest> should match 
// service_traits::DataType< ::cob_srvs::SetJointTrajectory > 
template<>
struct DataType< ::cob_srvs::SetJointTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetJointTrajectory >::value();
  }
  static const char* value(const ::cob_srvs::SetJointTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::SetJointTrajectoryResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::SetJointTrajectory > 
template<>
struct MD5Sum< ::cob_srvs::SetJointTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetJointTrajectory >::value();
  }
  static const char* value(const ::cob_srvs::SetJointTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetJointTrajectoryResponse> should match 
// service_traits::DataType< ::cob_srvs::SetJointTrajectory > 
template<>
struct DataType< ::cob_srvs::SetJointTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetJointTrajectory >::value();
  }
  static const char* value(const ::cob_srvs::SetJointTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_SETJOINTTRAJECTORY_H
