// Generated by gencpp from file cob_srvs/SetMaxVelRequest.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_SETMAXVELREQUEST_H
#define COB_SRVS_MESSAGE_SETMAXVELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_srvs
{
template <class ContainerAllocator>
struct SetMaxVelRequest_
{
  typedef SetMaxVelRequest_<ContainerAllocator> Type;

  SetMaxVelRequest_()
    : max_vel(0.0)  {
    }
  SetMaxVelRequest_(const ContainerAllocator& _alloc)
    : max_vel(0.0)  {
  (void)_alloc;
    }



   typedef float _max_vel_type;
  _max_vel_type max_vel;





  typedef boost::shared_ptr< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMaxVelRequest_

typedef ::cob_srvs::SetMaxVelRequest_<std::allocator<void> > SetMaxVelRequest;

typedef boost::shared_ptr< ::cob_srvs::SetMaxVelRequest > SetMaxVelRequestPtr;
typedef boost::shared_ptr< ::cob_srvs::SetMaxVelRequest const> SetMaxVelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_srvs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/melodic/share/trajectory_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4c36ffe76b55c7212cbc93d9e269be";
  }

  static const char* value(const ::cob_srvs::SetMaxVelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4c36ffe76b55c7ULL;
  static const uint64_t static_value2 = 0x212cbc93d9e269beULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_srvs/SetMaxVelRequest";
  }

  static const char* value(const ::cob_srvs::SetMaxVelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 max_vel\n"
;
  }

  static const char* value(const ::cob_srvs::SetMaxVelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMaxVelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_srvs::SetMaxVelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_srvs::SetMaxVelRequest_<ContainerAllocator>& v)
  {
    s << indent << "max_vel: ";
    Printer<float>::stream(s, indent + "  ", v.max_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_SRVS_MESSAGE_SETMAXVELREQUEST_H
