// Generated by gencpp from file cob_srvs/SetOperationMode.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_SETOPERATIONMODE_H
#define COB_SRVS_MESSAGE_SETOPERATIONMODE_H

#include <ros/service_traits.h>


#include <cob_srvs/SetOperationModeRequest.h>
#include <cob_srvs/SetOperationModeResponse.h>


namespace cob_srvs
{

struct SetOperationMode
{

typedef SetOperationModeRequest Request;
typedef SetOperationModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOperationMode
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::SetOperationMode > {
  static const char* value()
  {
    return "588a6152f0ed57d725118cc82be8479a";
  }

  static const char* value(const ::cob_srvs::SetOperationMode&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::SetOperationMode > {
  static const char* value()
  {
    return "cob_srvs/SetOperationMode";
  }

  static const char* value(const ::cob_srvs::SetOperationMode&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::SetOperationModeRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::SetOperationMode > 
template<>
struct MD5Sum< ::cob_srvs::SetOperationModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetOperationMode >::value();
  }
  static const char* value(const ::cob_srvs::SetOperationModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetOperationModeRequest> should match 
// service_traits::DataType< ::cob_srvs::SetOperationMode > 
template<>
struct DataType< ::cob_srvs::SetOperationModeRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetOperationMode >::value();
  }
  static const char* value(const ::cob_srvs::SetOperationModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::SetOperationModeResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::SetOperationMode > 
template<>
struct MD5Sum< ::cob_srvs::SetOperationModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::SetOperationMode >::value();
  }
  static const char* value(const ::cob_srvs::SetOperationModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::SetOperationModeResponse> should match 
// service_traits::DataType< ::cob_srvs::SetOperationMode > 
template<>
struct DataType< ::cob_srvs::SetOperationModeResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::SetOperationMode >::value();
  }
  static const char* value(const ::cob_srvs::SetOperationModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_SETOPERATIONMODE_H
