// Generated by gencpp from file cob_srvs/Trigger.msg
// DO NOT EDIT!


#ifndef COB_SRVS_MESSAGE_TRIGGER_H
#define COB_SRVS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <cob_srvs/TriggerRequest.h>
#include <cob_srvs/TriggerResponse.h>


namespace cob_srvs
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace cob_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_srvs::Trigger > {
  static const char* value()
  {
    return "bdad515e8f4c013bd650d3407753d2b8";
  }

  static const char* value(const ::cob_srvs::Trigger&) { return value(); }
};

template<>
struct DataType< ::cob_srvs::Trigger > {
  static const char* value()
  {
    return "cob_srvs/Trigger";
  }

  static const char* value(const ::cob_srvs::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::cob_srvs::TriggerRequest> should match 
// service_traits::MD5Sum< ::cob_srvs::Trigger > 
template<>
struct MD5Sum< ::cob_srvs::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::Trigger >::value();
  }
  static const char* value(const ::cob_srvs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::TriggerRequest> should match 
// service_traits::DataType< ::cob_srvs::Trigger > 
template<>
struct DataType< ::cob_srvs::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::Trigger >::value();
  }
  static const char* value(const ::cob_srvs::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_srvs::TriggerResponse> should match 
// service_traits::MD5Sum< ::cob_srvs::Trigger > 
template<>
struct MD5Sum< ::cob_srvs::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_srvs::Trigger >::value();
  }
  static const char* value(const ::cob_srvs::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_srvs::TriggerResponse> should match 
// service_traits::DataType< ::cob_srvs::Trigger > 
template<>
struct DataType< ::cob_srvs::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::cob_srvs::Trigger >::value();
  }
  static const char* value(const ::cob_srvs::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_SRVS_MESSAGE_TRIGGER_H
