// Generated by gencpp from file neo_msgs/IOBoard.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_IOBOARD_H
#define NEO_MSGS_MESSAGE_IOBOARD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct IOBoard_
{
  typedef IOBoard_<ContainerAllocator> Type;

  IOBoard_()
    : digital_inputs()
    , digital_outputs()
    , analog_inputs()  {
      digital_inputs.assign(false);

      digital_outputs.assign(false);

      analog_inputs.assign(0);
  }
  IOBoard_(const ContainerAllocator& _alloc)
    : digital_inputs()
    , digital_outputs()
    , analog_inputs()  {
  (void)_alloc;
      digital_inputs.assign(false);

      digital_outputs.assign(false);

      analog_inputs.assign(0);
  }



   typedef boost::array<uint8_t, 16>  _digital_inputs_type;
  _digital_inputs_type digital_inputs;

   typedef boost::array<uint8_t, 16>  _digital_outputs_type;
  _digital_outputs_type digital_outputs;

   typedef boost::array<uint8_t, 8>  _analog_inputs_type;
  _analog_inputs_type analog_inputs;





  typedef boost::shared_ptr< ::neo_msgs::IOBoard_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::IOBoard_<ContainerAllocator> const> ConstPtr;

}; // struct IOBoard_

typedef ::neo_msgs::IOBoard_<std::allocator<void> > IOBoard;

typedef boost::shared_ptr< ::neo_msgs::IOBoard > IOBoardPtr;
typedef boost::shared_ptr< ::neo_msgs::IOBoard const> IOBoardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::IOBoard_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::IOBoard_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/yusseff/Neobotix/src/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::IOBoard_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::IOBoard_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::IOBoard_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::IOBoard_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::IOBoard_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::IOBoard_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::IOBoard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfa16d6202dd05ce5b3fdebf8a7d44db";
  }

  static const char* value(const ::neo_msgs::IOBoard_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfa16d6202dd05ceULL;
  static const uint64_t static_value2 = 0x5b3fdebf8a7d44dbULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::IOBoard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/IOBoard";
  }

  static const char* value(const ::neo_msgs::IOBoard_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::IOBoard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message holds all data available from Neobotix IOBoard\n"
" \n"
"bool[16] digital_inputs			# state for all digital inputs\n"
"bool[16] digital_outputs		# state for all digital outputs\n"
"\n"
"uint8[8] analog_inputs			# analog input values\n"
"\n"
"\n"
;
  }

  static const char* value(const ::neo_msgs::IOBoard_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::IOBoard_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digital_inputs);
      stream.next(m.digital_outputs);
      stream.next(m.analog_inputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOBoard_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::IOBoard_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::IOBoard_<ContainerAllocator>& v)
  {
    s << indent << "digital_inputs[]" << std::endl;
    for (size_t i = 0; i < v.digital_inputs.size(); ++i)
    {
      s << indent << "  digital_inputs[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.digital_inputs[i]);
    }
    s << indent << "digital_outputs[]" << std::endl;
    for (size_t i = 0; i < v.digital_outputs.size(); ++i)
    {
      s << indent << "  digital_outputs[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.digital_outputs[i]);
    }
    s << indent << "analog_inputs[]" << std::endl;
    for (size_t i = 0; i < v.analog_inputs.size(); ++i)
    {
      s << indent << "  analog_inputs[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.analog_inputs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_IOBOARD_H
